### PR TITLE
Downgraded the Myriad to netstandard 2.0

### PR DESCRIPTION
**Pull request by Thecentury**
@7sharp9 What do you think about the idea to downgrade the netstandard from 2.1 to 2.0?

### CODE REVIEW

**Comment by 7sharp9** [comment]
Is it worth the effort, is this solely to appeal to more consumers?

**Comment by Thecentury** [comment]
It's difficult for me to decide if it is worth the effort. Do you think anything else should be changed besides the changes I made?
And yes, it is solely to widen the list of supported framework versions.
Netstandard 2.0 is the last one that is compatible with the old .NET framework.
With this change, it will become possible to use the library in .NET 4.6.1 projects and above.

**Comment by Zaid-Ajaj** [comment]
@7sharp9 `netstandard2.0` is a great default for class libraries

**Comment by 7sharp9** [comment]
Cool, done, Im all for more adoption.

Thanks! @Thecentury

**Pull request merged**
