### PR TITLE
Upgrade FSharp.Compiler.Service (now coming from Fantomas)

### PR DESCRIPTION
**Pull request by AlexeyRaga**
## Changes

- Upgrade `Fantomas` to the latest version (5.0.6)  
- Use `Fantomas.FCS` for `FSharp.Compiler.Services`.
  I think that it is an inevitable way to move forward because is we want to continue using `Fantomas` because since `v5.0` they started re-packaging and exposing their copy of `FSharp.Compiler.Services`. Which, perhaps, is not a bad deal for us because now we can _only_ depend on `Fantomas` instead of solving for compatible versions for both `Fantomas` and `FSharp.Compiler.Services`.

There were a few changes around trivias and renaming `LongIdentWithDots` to `SynLongIdent`. I don't know why MS decided to publish it as a minor version update because it is a breaking change.

There are also a couple of fixes in lens/DU generators, mainly around return types. These bugs didn't surface because of another bug around trivias, when the return type wasn't printed. But it was specified incorrectly :)

### CODE REVIEW

**Comment by AlexeyRaga** [comment]
I am getting this strange error:

```
Error: /home/runner/work/myriad/myriad/src/Myriad/Program.fs(217,58): error FS0001: This expression was expected to have type    'FSharp.Compiler.Syntax.ParsedInput (Fantomas.FCS, Version=5.0.6.0, Culture=neutral, PublicKeyToken=null)'    but here has type    'FSharp.Compiler.Syntax.ParsedInput (FSharp.Compiler.Service, Version=41.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)' [/home/runner/work/myriad/myriad/src/Myriad/Myriad.fsproj] [/home/runner/work/myriad/myriad/build.proj]
```

Looking at `Fantomas` and I see that it re-packages `FSharp.Compiler.Service` (literally, gets the sources and builds them without referencing the official stuff).

@7sharp9 Since Myriad uses Fantomas heavily, are we interested to porting it to `FSharp.Compiler.Service` from `Fantomas`?

**Comment by AlexeyRaga** [comment]
@7sharp9 Looks like it is OK now. It deserves major version bump (because MS broke `FSharp.Compiler.Services` API) if we decide to merge it.

**Comment by 7sharp9** [comment]
Thanks!

**Comment by 7sharp9** [comment]
I had no notification so never saw this, thanks though, fantomas can be a huge pain when they break something thats used upstream, its happened quite often so I dont tend to upgrade often.

**Pull request merged**
